### ISSUE TITLE
Deals custom fields names not populated 

### ISSUE THREAD

**Issue by TomaszE** [singer-io/tap-pipedrive#23]
Hi,
We got a problem with our pipedrive integration - we have few different campaigns build in to the pipedrive, which have forced us to add some custom fields in to the pipedrive deals.
All custom fields unfortunately are pulled in below way:

`22bd649b7f9cf4edb4181d3673090ba95a7e20d1`
`b84184cbc4786008094347b18b2cedaba85dbb`
`32b84184cbc4786008094347b18b2cedaba85dbb`

![image](https://user-images.githubusercontent.com/29064508/41360416-a27dd87a-6f24-11e8-9587-41df612d0c52.png)

is it possible to pull name instead of id ( I'm guessing it's an id ) .

in the Pipedrive itself its looking like below:

![image](https://user-images.githubusercontent.com/29064508/41360854-98c1fab8-6f25-11e8-807f-23254a294476.png)

I have no possibility to edit or change Field API key

Thanks

**Comment by dmosorast** [comment]
Hi @TomaszE, it should be possible to map the name to the Id of these fields and emit records using the name instead of the ID. Judging from the Pipedrive [API Docs](https://pipedrive.readme.io/docs/core-api-concepts-custom-fields), Pipedrive refers to them only by this name.

So, depending on the data returned by [this endpoint](https://developers.pipedrive.com/docs/api/v1/#!/DealFields), it could be as simple as getting the name from a different `key` [here](https://github.com/singer-io/tap-pipedrive/blob/master/tap_pipedrive/streams/recents/dynamic_typing/__init__.py#L29), or there might be a different request to make at that time.

Feel free to give this a shot and submit a Pull Request! The Singer slack channel is a good resource if you need assistance.

**Comment by TomaszE** [comment]
HI @dmosorast , thank you, unfortunately most of the above is a black magic for me. I'm Stitch user,  with basic understanding, I came here, as I do not think I will be able to pull the request directly.

As per endpoint it's returning something like below:

`"id": 12498,
"key": "d80027fcd0c4b73c0a33b370077b9a2d3fd26867",
"name": "Test123",
"order_nr": 1,
"field_type": "varchar",
"add_time": "2018-06-13 15:19:02",
"update_time": "2018-06-13 15:19:02",
"active_flag": true,
"edit_flag": true,
"index_visible_flag": true,
"details_visible_flag": true,
"add_visible_flag": false,
"important_flag": false,
"bulk_edit_allowed": true,
"searchable_flag": true,
"filtering_allowed": true,
"sortable_flag": true,
"mandatory_flag": false`

for every single DealField.

**Comment by ajmers** [comment]
@TomaszE I opened a PR (https://github.com/singer-io/tap-pipedrive/pull/25) to update the tap to check whether the id beings w/ a 40-digit hexadecimal string like the one above, and if so, use the `name` field instead. I'll update this issue when the fix has gone out!

**Comment by TomaszE** [comment]
Hey @ajmers - thanks for you help - any idea when can we expect the fix to go life?

**Comment by timvisher** [comment]
@TomaszE I'm working on this currently. I want to make sure I understand the best way to support your use case.

I understand that you're frustrated by Pipedrive's use of a uuid to refer to custom fields in your `deal` data. I can't speak with certainty to exactly why they're doing so but one potential reason is that they wanted to give you the ability to name multiple custom fields the same thing rather than forcing custom field names to be globally unique. If the names of the fields are not globally unique translating from the UUID to the name would potentially cause field collisions which would be very bad for your data.

If this is the case then I think the best solution here would actually be to emit an additional stream `DealFields` which would allow you to directly refer to the name of a given custom field. This would be the safest option and wouldn't violate the way their API appears to want to work.

The only tradeoff with that solution that I can think of at the moment would be that you would need to query the data dynamically if you wanted to use the name rather than the uuid as the selector. You may already be in that situation though if the name is not required to be unique.

What do you think?

**Comment by timvisher** [comment]
Closing this based on lack of feedback.

**Comment by alb150** [comment]
Hi,

I am also looking into a solution for this issue. Was any fix published?

Thanks

**Comment by jmace006** [comment]
Hi there, this is also a problem for us, keen to see if there was any update. Thanks.
